---
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--check]
        files: \.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        files: \.py$

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff lint (dbt templater)
        args:
          - --dialect=bigquery
          - --templater=dbt
          - --nocolor
        additional_dependencies:
          - sqlfluff-templater-dbt
          - dbt-bigquery
        stages: [commit]

      - id: sqlfluff-lint
        name: sqlfluff lint (jinja templater)
        args:
          - --dialect=bigquery
          - --templater=jinja
          - --nocolor
        stages: [manual]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict]
        files: \.(yml|yaml)$
        exclude: ^\.github/
