---
name: Lint & Format Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Prepare dbt profile
        run: |
          mkdir -p ~/.dbt
          cp .github/dbt_profiles_dummy.yml ~/.dbt/profiles.yml

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
