---
name: Lint & Format Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run default hooks (push stage)
        run: pre-commit run --all-files --hook-stage push

      - name: Run sqlfluff (jinja templater only)
        run: |
          pre-commit run sqlfluff-lint --all-files --hook-stage manual
